//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func main() {
	homeDir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}

	langPath := homeDir + "/.knowledge/minecraft-data/data/pc/1.21.11/language.json"
	if len(os.Args) > 1 {
		langPath = os.Args[1]
	}

	data, err := os.ReadFile(langPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading language.json: %v\n", err)
		os.Exit(1)
	}

	var langMap map[string]string
	if err := json.Unmarshal(data, &langMap); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing language.json: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("// Code generated by go run generate_lang.go. DO NOT EDIT.")
	fmt.Println("// Source: .knowledge/minecraft-data/data/pc/1.21.11/language.json")
	fmt.Println("// Minecraft version: 1.21.11, Protocol: 774")
	fmt.Println()
	fmt.Println("package i18n")
	fmt.Println()
	fmt.Println("func getLangData(lang string) []langEntry {")
	fmt.Println("\tswitch lang {")
	fmt.Println("\tcase \"en_us\":")
	fmt.Println("\t\treturn []langEntry{")

	count := 0
	for key, value := range langMap {
		if shouldIncludeKey(key) {
			safeKey := escapeString(key)
			safeValue := escapeString(value)
			fmt.Printf("\t\t\t{Key: \"%s\", Value: \"%s\"},\n", safeKey, safeValue)
			count++
		}
	}

	fmt.Println("\t\t}")
	fmt.Println("\tdefault:")
	fmt.Println("\t\treturn []langEntry{}")
	fmt.Println("\t}")
	fmt.Println("}")

	fmt.Fprintf(os.Stderr, "Generated %d language entries\n", count)
}

func shouldIncludeKey(key string) bool {
	prefixes := []string{
		"chat.",
		"death.",
		"item.minecraft.",
		"block.minecraft.",
		"entity.minecraft.",
		"biome.minecraft.",
		"effect.minecraft.",
		"enchantment.minecraft.",
		"gamerule.",
		"commands.",
		"argument.",
		"potion.",
		"container.",
		"itemGroup.",
		"stat.",
		"advancement.",
		"recipe.",
		"message.",
		"multiplayer.",
		"options.",
		"select.",
		"tutorial.",
	}
	for _, prefix := range prefixes {
		if strings.HasPrefix(key, prefix) {
			return true
		}
	}
	return false
}

func escapeString(s string) string {
	result := ""
	for _, c := range s {
		switch c {
		case '"':
			result += `\"`
		case '\\':
			result += `\\`
		case '\n':
			result += `\n`
		case '\r':
			result += `\r`
		case '\t':
			result += `\t`
		default:
			if c >= 32 && c <= 126 {
				result += string(c)
			} else {
				result += `\u` + strconv.FormatInt(int64(c), 16)
			}
		}
	}
	return result
}
