//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type itemEntry struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	StackSize   int32  `json:"stackSize"`
}

func main() {
	homeDir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}

	itemsPath := homeDir + "/.knowledge/minecraft-data/data/pc/1.21.11/items.json"
	if len(os.Args) > 1 {
		itemsPath = os.Args[1]
	}

	data, err := os.ReadFile(itemsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading items.json: %v\n", err)
		os.Exit(1)
	}

	var items []itemEntry
	if err := json.Unmarshal(data, &items); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing items.json: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("// Code generated by go run generate_items.go. DO NOT EDIT.")
	fmt.Println("// Source: .knowledge/minecraft-data/data/pc/1.21.11/items.json")
	fmt.Println("// Minecraft version: 1.21.11, Protocol: 774")
	fmt.Println()
	fmt.Println("package registry")
	fmt.Println()
	fmt.Println("func getItemsData() []itemEntry {")
	fmt.Println("\treturn []itemEntry{")

	for _, item := range items {
		name := safeString(item.Name)
		displayName := safeString(item.DisplayName)
		fmt.Printf("\t\t{ID: %d, Name: \"%s\", DisplayName: \"%s\", StackSize: %d},\n",
			item.ID, name, displayName, item.StackSize)
	}

	fmt.Println("\t}")
	fmt.Println("}")
}

func safeString(s string) string {
	result := ""
	for _, c := range s {
		switch c {
		case '"':
			result += `\"`
		case '\\':
			result += `\\`
		case '\n':
			result += `\n`
		case '\r':
			result += `\r`
		case '\t':
			result += `\t`
		default:
			if c >= 32 && c <= 126 {
				result += string(c)
			}
		}
	}
	return result
}
